version: '3.8'

services:
  backend:
    build: ./backend
    container_name: scale_backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: scale_frontend
    restart: unless-stopped
    expose:
      - "80"

  nginx:
    image: nginx:stable-alpine
    container_name: scale_nginx
    restart: unless-stopped
    # Porta SOMENTE interna via loopback (sem 443)
    ports:
      - "127.0.0.1:8091:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:15
    container_name: scale_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  static_volume:
  media_volume:
