# Generated by Django 5.2.5 on 2025-08-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('volume_padrao', models.CharField(max_length=20)),
                ('unidade_medida', models.CharField(max_length=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=50)),
                ('pesador', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('bruto', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tara', models.DecimalField(decimal_places=3, max_digits=10)),
                ('liquido', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('volume', models.CharField(max_length=50)),
                ('balanca', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(default='TEMP', max_length=50)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.materiaprima')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.produto')),
            ],
        ),
    ]
