# Generated by Django 5.2.5 on 2025-08-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('tipo_conexao', models.CharField(choices=[('ethernet', 'Ethernet'), ('serial', 'Serial'), ('usb', 'USB')], default='ethernet', max_length=20)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('porta', models.PositiveIntegerField(blank=True, null=True)),
                ('porta_serial', models.CharField(blank=True, default='', max_length=50)),
                ('localizacao', models.CharField(blank=True, default='', max_length=100)),
                ('capacidade_maxima', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('divisao', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('protocolo', models.CharField(blank=True, default='', max_length=50)),
                ('ultima_calibracao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balança',
                'verbose_name_plural': 'Balanças',
            },
        ),
        migrations.CreateModel(
            name='EstruturaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=50, unique=True)),
                ('lote', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('estrutura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops', to='registro.estruturaproduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops', to='registro.produto')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantidade_pesada', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unidade', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L'), ('un', 'un')], default='kg', max_length=10)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.materiaprima')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.ordemproducao')),
            ],
            options={
                'unique_together': {('op', 'materia_prima')},
            },
        ),
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesador', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('bruto', models.DecimalField(decimal_places=3, max_digits=14)),
                ('tara', models.DecimalField(decimal_places=3, max_digits=14)),
                ('liquido', models.DecimalField(decimal_places=3, default=0.0, max_digits=14)),
                ('volume', models.CharField(blank=True, default='', max_length=50)),
                ('codigo_interno', models.CharField(default='TEMP', max_length=50)),
                ('balanca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesagens', to='registro.balanca')),
                ('item_op', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pesagens', to='registro.itemop')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesagens', to='registro.ordemproducao')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddField(
            model_name='estruturaproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estruturas', to='registro.produto'),
        ),
        migrations.CreateModel(
            name='ItemEstrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_por_lote', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unidade', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L'), ('un', 'un')], default='kg', max_length=10)),
                ('estrutura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='registro.estruturaproduto')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_estrutura', to='registro.materiaprima')),
            ],
            options={
                'unique_together': {('estrutura', 'materia_prima')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='estruturaproduto',
            unique_together={('produto', 'descricao')},
        ),
    ]
