# Generated by Django 5.2.5 on 2025-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesagem',
            name='lote_mp',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador do lote da matéria-prima usado nesta pesagem (ex.: 24A0321).', max_length=60, verbose_name='lote_MP'),
        ),
        migrations.AddIndex(
            model_name='pesagem',
            index=models.Index(fields=['item_op', 'lote_mp'], name='registro_pe_item_op_0b60dc_idx'),
        ),
    ]
