# Generated by Django 5.2.5 on 2025-08-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('tipo_conexao', models.CharField(choices=[('ethernet', 'Ethernet'), ('serial', 'Serial'), ('usb', 'USB')], default='ethernet', max_length=20)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('porta', models.PositiveIntegerField(blank=True, null=True)),
                ('porta_serial', models.CharField(blank=True, default='', max_length=50)),
                ('localizacao', models.CharField(blank=True, default='', max_length=100)),
                ('capacidade_maxima', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('divisao', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('protocolo', models.CharField(blank=True, default='', max_length=50)),
                ('ultima_calibracao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Balança',
                'verbose_name_plural': 'Balanças',
            },
        ),
    ]
