# Generated by Django 5.2.5 on 2025-08-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_units_to_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemestrutura',
            name='unidade',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L'), ('un', 'un')], default='g', help_text="Regra do projeto: utilizar 'g' para MPs.", max_length=10),
        ),
        migrations.AlterField(
            model_name='itemop',
            name='unidade',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L'), ('un', 'un')], default='g', help_text='Sempre g.', max_length=10),
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='bruto',
            field=models.DecimalField(decimal_places=3, help_text='Valor em kg lido na balança (entrada do operador).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='liquido',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Valor calculado e armazenado em g.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='tara',
            field=models.DecimalField(decimal_places=3, help_text='Valor em kg da tara (entrada do operador).', max_digits=14),
        ),
    ]
