# Generated by Django 5.2.5 on 2025-08-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_pesagem_balanca_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesagem',
            name='balanca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesagens', to='registro.balanca'),
        ),
    ]
