# Generated by Django 5.2.5 on 2025-08-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_fix_defaults_to_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemestrutura',
            name='unidade',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L'), ('un', 'un')], default='g', help_text="Regra do projeto: utilizar 'g' para MPs.", max_length=10),
        ),
    ]
