# Generated by Django 5.2.5 on 2025-08-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_add_codigo_interno_materia_prima_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='unidade_medida',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='volume_padrao',
        ),
    ]
