# Generated by Django 5.2.5 on 2025-08-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_itemestrutura_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesagem',
            name='bruto',
            field=models.DecimalField(decimal_places=3, help_text='Calculado automaticamente no backend (kg): tara_kg + liquido_kg.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='liquido',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Armazenado em g (entrada do operador é em kg; o backend converte).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='tara',
            field=models.DecimalField(decimal_places=3, help_text='Entrada do operador em kg.', max_digits=14),
        ),
    ]
