# Generated by Django 5.2.5 on 2025-08-20 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_remove_produto_unidade_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesagem',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesagens', to='registro.materiaprima'),
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesagens', to='registro.produto'),
        ),
    ]
