# Generated by Django 5.2.5 on 2025-09-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_pesagem_bruto_alter_pesagem_liquido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesagem',
            name='volume',
        ),
    ]
