# Generated by Django 5.2.5 on 2025-10-23 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_remove_pesagem_volume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=32)),
                ('model', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('object_pk', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='registro_au_timesta_74eef3_idx'), models.Index(fields=['model', 'object_pk'], name='registro_au_model_4d0f76_idx')],
            },
        ),
    ]
