# Generated by Django 5.2.5 on 2025-10-23 18:29

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log de Auditoria', 'verbose_name_plural': 'Logs de Auditoria'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Alterações'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='extra',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Informações extras'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='method',
            field=models.CharField(max_length=8, verbose_name='Método HTTP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Modelo afetado'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_pk',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='PK do objeto'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='path',
            field=models.CharField(db_index=True, max_length=512, verbose_name='Rota/Endpoint'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código de status'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='User-Agent'),
        ),
    ]
