# Generated by Django 5.2.5 on 2025-11-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_alter_auditlog_options_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesagem',
            name='lote_mp',
            field=models.CharField(db_index=True, help_text='Identificador do lote da matéria-prima usado nesta pesagem (ex.: 24A0321).', max_length=60, verbose_name='lote_MP'),
        ),
    ]
