# Generated by Django 5.2.5 on 2025-11-20 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_backuprecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Backup automático ativo')),
                ('schedule_type', models.CharField(choices=[('daily', 'Diário em horário fixo'), ('interval', 'Intervalo em horas')], default='daily', max_length=20, verbose_name='Tipo de agendamento')),
                ('time_of_day', models.TimeField(default=datetime.time(3, 0), help_text='Horário diário para execução do backup.', verbose_name='Horário (hora local)')),
                ('interval_hours', models.PositiveIntegerField(default=24, help_text='Executa a cada X horas (usado no modo Intervalo).', verbose_name='Intervalo (horas)')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='(Futuro) Quantos dias manter backups antes de limpeza automática.', verbose_name='Retenção (dias)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Backup Automático',
                'verbose_name_plural': 'Configuração de Backup Automático',
            },
        ),
    ]
