# Generated by Django 5.2.5 on 2026-04-21 00:23

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_balanca_frequencia_calibracao_e_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('engine', models.CharField(max_length=50)),
                ('output_file', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], default='success', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('path', models.CharField(db_index=True, max_length=512, verbose_name='Rota/Endpoint')),
                ('method', models.CharField(max_length=8, verbose_name='Método HTTP')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Código de status')),
                ('action', models.CharField(db_index=True, max_length=32, verbose_name='Ação')),
                ('model', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Modelo afetado')),
                ('object_pk', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='PK do objeto')),
                ('changes', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Alterações')),
                ('extra', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Informações extras')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='registro_au_timesta_74eef3_idx'), models.Index(fields=['-timestamp'], name='registro_au_timesta_198a28_idx'), models.Index(fields=['action'], name='registro_au_action_b53e72_idx'), models.Index(fields=['method'], name='registro_au_method_dc1eee_idx'), models.Index(fields=['model'], name='registro_au_model_2bdd4c_idx'), models.Index(fields=['status_code'], name='registro_au_status__a8c75d_idx'), models.Index(fields=['path'], name='registro_au_path_5f1919_idx'), models.Index(fields=['user'], name='registro_au_user_id_f78ac5_idx'), models.Index(fields=['object_pk'], name='registro_au_object__95d60e_idx'), models.Index(fields=['ip'], name='registro_au_ip_7e935d_idx'), models.Index(fields=['model', 'object_pk'], name='registro_au_model_4d0f76_idx')],
            },
        ),
    ]
