# Generated by Django 5.2.5 on 2026-04-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_backupconfig'),
        ('registro', '0018_backupconfig_default_enabled'),
    ]

    operations = [
    ]
