# Generated by Django 5.2.5 on 2026-04-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0019_merge_20260427_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupconfig',
            name='retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Quantos dias manter backups antes de deletar.', verbose_name='Retenção (dias)'),
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='lote_mp',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador do lote da matéria-prima usado nesta pesagem (ex.: 24A0321).', max_length=60, verbose_name='lote_MP'),
        ),
    ]
