# Generated by Django 5.2.5 on 2026-09-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0024_alter_pesagem_liquido_precisao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemestrutura',
            name='quantidade_por_lote',
            field=models.DecimalField(decimal_places=6, help_text='Sempre em g. decimal_places=6 (resolucao de 1 ug) porque micro-ingredientes como vitaminas entram na formula em dezenas de microgramas.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemop',
            name='quantidade_necessaria',
            field=models.DecimalField(decimal_places=6, help_text='Em g. Copiada de ItemEstrutura.quantidade_por_lote; acompanha a mesma precisao para a formula nao chegar truncada na OP.', max_digits=14),
        ),
    ]
