# Generated by Django 5.2.5 on 2026-04-21 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Tela',
                'verbose_name_plural': 'Telas',
            },
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='papel',
            field=models.CharField(choices=[('operador', 'Operador'), ('supervisor', 'Supervisor'), ('admin', 'Administrador')], default='operador', max_length=20),
        ),
        migrations.CreateModel(
            name='LoginSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_logins', models.PositiveIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Segurança de Login',
                'verbose_name_plural': 'Segurança de Login',
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='usuarios.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='screens',
            field=models.ManyToManyField(blank=True, related_name='roles', to='usuarios.screen'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='extra_screens',
            field=models.ManyToManyField(blank=True, related_name='perfis_extra', to='usuarios.screen'),
        ),
    ]
