# Generated by Django 5.2.5 on 2025-10-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Papel',
                'verbose_name_plural': 'Papéis',
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Tela',
                'verbose_name_plural': 'Telas',
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='usuarios.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='screens',
            field=models.ManyToManyField(blank=True, related_name='roles', to='usuarios.screen'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='extra_screens',
            field=models.ManyToManyField(blank=True, related_name='perfis_extra', to='usuarios.screen'),
        ),
    ]
