# Generated by Django 5.2.5 on 2025-10-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_role_screen_perfilusuario_roles_role_screens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='papel',
            field=models.CharField(choices=[('operador', 'Operador'), ('supervisor', 'Supervisor'), ('admin', 'Administrador')], default='operador', max_length=20),
        ),
    ]
