# Generated by Django 5.2.5 on 2025-11-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_loginsecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsecurity',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginsecurity',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
