# Generated by Django 5.2.5 on 2026-04-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_role_screen_alter_perfilusuario_papel_loginsecurity_and_more'),
        ('usuarios', '0005_loginsecurity_last_password_change_and_more'),
    ]

    operations = [
    ]
